version: "3"

volumes:
  mongodata:

networks:
  mongodb_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge

services:
  # todo: add nginx container
  bot:
    build: .
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - ./cfg/bot/:/home/bot/config:ro
      - ./codexbot:/home/bot/codexbot:ro
      - ./i18n:/home/bot/i18n:ro
    networks:
      - mongodb_network
      - rabbitmq_network
    environment:
      BOT_CONFIG_FILE_PATH: "/home/bot/config/global.yml"
      BOT_TELEGRAM_CONFIG_FILE_PATH: "/home/bot/config/telegram/config.yml"
      BOT_SLACK_CONFIG_FILE_PATH: "/home/bot/config/slack/config.yml"
    ports:
      - 1337:1337
    restart: on-failure # todo: start bot only after rabbitmq has started
    command: "python -m codexbot"

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodata:/data/db
    networks:
      - mongodb_network

  rabbitmq:
    image: rabbitmq:alpine
    networks:
      - rabbitmq_network
