name: Build and push docker image

on: [push]

env:
  DOCKER_REPO: codex-team/codex-bot-core

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push production image
        if: endsWith(github.ref, '/prod')
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ env.DOCKER_REPO }}:prod
          push: ${{ endsWith(github.ref, '/prod') }}

      - name: Build and push stage image
        if: endsWith(github.ref, '/stage')
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ env.DOCKER_REPO }}:stage
          push: ${{ endsWith(github.ref, '/stage') }}